---
title: "STAT 321 Blackjack Project Report"
output: pdf_document
---
Alejandro Herrle

Martin Steffens

Charles Hwang

Dr. Matthews

STAT 321-001

10 December 2019

(1) Introduction: We wanted to see what type of general playing strategy in the game of blackjack is the most successful. Since the optimal strategy of blackjack is already known, we wanted to see the differences in success between different strategies.

(2) Methods: We simulated three different strategies: “softie”, “reckless”, and “optimized”. The player using the “softie” strategy always stands and the player using the “reckless” strategy stands on 20. However, the player using the “optimized” strategy is more complicated. If this player has an ace, he/she stands on 18. If this player does not have an ace, he/she stands on 17, stands on 13 if the dealer’s upcard is a 6 or lower, and stands on exactly 12 if the dealer’s upcard is between 4 and 6. We simulated these three strategies with one deck and one player. All of the code for this simulation can be found in the (5) Appendix of this report.
 
(3) Results: We simulated the three strategies. While all three strategies still leave the house with more money in their pocket, the following is the order from least to best “softie” , “reckless”, and “optimized”.  Less than 10% is lost in “optimized” where almost 50% is lost in “softie”.  

(4) Conclusions/Future Work: We conclude that the optimized strategy is the most successful strategy, as expected. There are many different things we would do in a similar project in the future if we had more time, including:
* Performing a higher number of simulations
* Simulating with different numbers of decks
* Simulating with different numbers of players
* Devising other playing strategies
* Incorporating splitting and doubling down
    + Insurance and surrendering could also be added, but we feel these are more difficult to properly simulate in R and possibly add another dimension to the problem which may confound the results.

## (5) Appendix

```{r Appendix}
blackjack <- function(decks=1,players=1,strategy=""){
  deal <- function(players){
    for (i in players+1){
      cards <- sample(rep(c(2,3,4,5,6,7,8,9,10,10,10,10,11),4 * decks),2*i,replace=FALSE)
      out <- matrix(cards,nrow=i)
      down <- out[i,1] 
      out[i,1] <- 0
      return(out)
    }
  }
  newcardsoft <- sample(rep(c(2,3,4,5,6,7,8,9,10,10,10,10,11),4*decks),1,replace=FALSE)
  newcardhard <- sample(rep(c(1,2,3,4,5,6,7,8,9,10,10,10,10),4*decks),1,replace=FALSE)
  D <- deal(players)
  if (strategy == "softie"){
    D <- deal(1)
    myhand <- sum(D[1,])
    #This player will never hit
    #print("Softie Hand")
    #print(myhand)
    if(myhand == 22) {
      myhand = 12
    }
    if (myhand == 21){
      myhand <- 21.5 # Blackjack is defined as "21.5" in this function
    }
  }
  if(strategy == "reckless"){
    D <- deal(1)
    myhand <- sum(D[1,])
    #This player will hit until 20 or 21
    #print("Reckless Hand")
    #print(myhand)
    if (myhand == 22) {
      myhand = 12
    }
    if (myhand == 21){
      myhand <- 21.5 # Blackjack is defined as "21.5" in this function
    }
    while(myhand < 20){
    if (myhand < 11){
      myhand <- myhand + newcardsoft
      #print(myhand)
    }
    if (myhand >= 11){
      myhand <- myhand + newcardhard
      #print(myhand)
    }
    }
  }
  if(strategy == "optimized") {
    #print("optimized hand")
    D = deal(1)
    down = D[-1,1]
    myhand = sum(D[1,])
    if (myhand == 22) {
      myhand = 12
    }
    else if (myhand == 21) {
      myhand = 21.5
    }
    hasAce = 11 %in% D[1,]
    stand = FALSE
    #print(hasAce)
    while ((stand != TRUE) & (myhand < 21)) {
      #print(myhand)
      if (hasAce == TRUE) {
        if (myhand >= 18) {
          stand = TRUE
        }
        else if(myhand == 18) {
          if (down <= 8) {
            stand = TRUE
          }
          else {
            myhand = myhand + newcardsoft
            if (myhand > 21) {
              myhand = myhand - 10
            }
            else if (myhand > 11) {
              hasAce = FALSE            }
          }
        }
        else if(myhand > 10) {
          myhand = myhand + newcardsoft
          if (myhand > 21) {
            myhand = myhand - 10
            hasAce = FALSE
          }
          if (myhand > 11) {
            hasAce = FALSE
          }
        }
        else {
          newCard = newcardhard
          if (newCard == 11) {
            hasAce = TRUE
          }
          myhand = myhand + newCard
        }
        
      }
      else {
        if (myhand >= 17) {
          stand = TRUE
        }
        else if (myhand >= 13) {
          if (down <=6) {
            stand = TRUE
          } else {
            myhand = myhand + newcardsoft
          }
        } 
        else if (myhand == 12) {
          if (down >= 4 && down <= 6) {
            stand = TRUE
          }
          else {
            myhand = myhand + newcardsoft
          }
        }
        else if (myhand == 11) {
          myhand = myhand + newcardsoft
        } 
        else {
          newCard = newcardhard
          if (newCard == 11) {
            hasAce = True
          }
          myhand = myhand + newCard
          
        }
      }
      if(stand == TRUE) {
      }
    }}
  
  
  house <- sum(D[-1,])
  if (house == 22) {
    house = 12
  }
  #print("House Hand")
  #print(house)
  if (myhand > 21.5) {
    #print("You bust")
    return(-1)
  }
  if (house == 21){
    house <- 21.5 # Blackjack is defined as "21.5" in this function
    if (myhand != 21.5){
      #print("House blackjack. Therefore:")
      #print("You lose. Sad!")
      return(-1)
    }
    else {
      #print("both blackjack. Push")
      return(0)
    }
  }
  if (myhand == 21.5 & house != 21.5){
    #print("BLACKJACK!")
    return(1.5)
  }
  while(house < 17){
    #cat("house less than 17. hitting on", house)
    if (house < 11){
      house <- house + newcardsoft
      #print(house)
    }
    else {
      house <- house + newcardhard
      #print(house)
    }
  }
  if (myhand <= 21.5 & house > 21.5) {
    return(1)
  }
  
  if (myhand > house){
    #print("You win. Nice!")
    return(1)
  }
  if (myhand == house){
    #print("You push. Sad!")
    return(0)
  }
  if (myhand < house & house <= 21){
    #print("You lose. Sad!")
    return(-1)
  }
}
trials = 100000
sB = 0
rB = 0 
oB = 0
for (val in 1:trials) {
  sB = sB + blackjack(decks=1, players=1, strategy = "softie")
  rB = rB + blackjack(decks=1, players = 1, strategy = "reckless")
  oB = oB + blackjack(decks=1,players=1,strategy="optimized")
}
sB/trials #house edge for the “softie” strategy
rB/trials #house edge for the “reckless” strategy 
oB/trials #house edge for the “optimized (basic play)” strategy
```