---
title: "STAT 321"
output: html_document
---
Charles Hwang

Professor Matthews

STAT 321-001

20 September 2019

## Exercise 3a

```{r Exercise 3a}
rm(list=ls())
r <- rep(0,4)
r[1] <- ceiling(6*runif(1))
r[2] <- ceiling(6*runif(1))
r[3] <- ceiling(6*runif(1))
r[4] <- ceiling(6*runif(1))
print(r[1])
print(r[2])
print(r[3])
print(r[4])
if (r[1] == 6 | r[2] == 6 | r[3] == 6 | r[4] == 6){
  cat("You won. Nice!")
} else {
  cat("You lost. Sad!")
}
```

## Exercise 3b

```{r Exercise 3b, message=FALSE, warning=FALSE}
rm(list=ls())
library(purrr)
sixes <- function(n = 4){
  i <- 1
  r <- rep(0,n)
  x <- rep(0,n)
  while (i <= n){
    r[i] <- ceiling(6*runif(1))
    print(r[i])
    i <- i + 1
  }
  has_element(r,6)
}
sixes()
```

## Exercise 3c
### Part 1

```{r Exercise 3c(a)}
rm(list=ls())
sixes <- function(n = 4){
  i <- 1
  r <- rep(0,n)
  x <- rep(0,n)
  while (i <= n){
    r[i] <- ceiling(6*runif(1)) # Did not print rolls to prevent 33,300 rolls from being printed
    i <- i + 1
  }
  has_element(r,6)
}
sixesN <- function(n = 4,N = 3){ # Roll four dice three times by default
  cat("Proportion:", mean(replicate(N,sixes(n))))
}
sixesN()

sixesN(4,100)
sixesN(4,100)
sixesN(4,100)
sixesN(4,1000)
sixesN(4,1000)
sixesN(4,1000)
sixesN(4,10000)
sixesN(4,10000)
sixesN(4,10000)
# The variability decreases as N increases.
```

### Part 2

```{r Exercise 3c(b)}
rm(list=ls())
sixes <- function(n = 4){
  i <- 1
  r <- rep(0,n)
  x <- rep(0,n)
  while (i <= n){
    r[i] <- ceiling(6*runif(1)) # Did not print rolls to prevent 11,100 rolls from being printed
    i <- i + 1
  }
  has_element(r,6)
}
sixesN <- function(n = 4,N = 3){
  est <- mean(replicate(N,sixes(n))) # "Simulation estimate"
  cat("Estimate:", est, "\n")
  p <- 1 - (5/6)^n                   # "Theoretical probability"
  cat("Probability:", p, "\n")
  cat("Difference:", abs(p - est))
}
sixesN()

sixesN(4,100)
sixesN(4,1000)
sixesN(4,10000)
# The accuracy increases as N increases.
```

## Exercise 3d

```{r Exercise 3d, message=FALSE,warning=FALSE}
rm(list=ls())
library(car)
library(plyr)
sixes <- function(n = 4){
  i <- 1
  r <- rep(0,n)
  x <- rep(0,n)
  while (i <= n){
    r[i] <- ceiling(6*runif(1))
    i <- i + 1
  }
  has_element(r,6)
}
sixesN <- function(n = 4,N = 3){
  Export(data.frame(replicate(N,sixes(n))),"sixes_sim.txt") # Creating .txt file without printing results in R
}
sixesN(4,11103) # "N" not specified, so I chose 11,103 = 3 + 100 + 1,000 + 10,000

data <- read.table(file="/Users/newuser/Desktop/sixes_sim.txt", header=TRUE)
m <- count(data)/lengths(data) # Manually calculating the mean
m[2,2]
```

## Exercise 5

```{r Exercise 5, message=FALSE, warning=FALSE}
rm(list=ls())
library(ggplot2)
library(gridExtra)
sys <- function(x1 = 0.1,r = 1,n = 99){
x <- rep(NA,n)
  for (i in 1:n){
    if (i == 1) {
      x[1] = x1
      print(x[i])
    } else if (i == n) {
      print(x[i])
      cat("\n") # Separate each run of the function
      } else {
        x[i] = r*x[i-1]*(1 - x[i-1])
        print(x[i])
      }
    }
return(ggplot(data.frame(X = c(1:n), Y = x),aes(X,Y))+geom_point()+ylab("x[n]")+xlab("n")+ggtitle("",subtitle = r))
}
sys()
grid.arrange(sys(0.9,1.5),sys(0.9,2.9),sys(0.9,3.1),sys(0.9,3.5),sys(0.9,3.56),sys(0.9,3.57),sys(0.9,3.58),sys(0.9,3.8),sys(0.9,4))
```

## Problem 3

```{r Problem 3}
rm(list=ls())
hist(mtcars$mpg)
library(ggplot2)
ggplot(data=mtcars, aes(mpg))+geom_histogram(binwidth=5) # Arbitrary bin width chosen
```

## Problem 4

```{r Problem 4}
rm(list=ls())
plot(mtcars$mpg,mtcars$wt)
library(ggplot2)
ggplot(data=mtcars,aes(mpg,wt))+geom_point()
```

## Problem 5

```{r Problem 5, message=FALSE, warning=FALSE}
rm(list=ls())
ggplot(data=mtcars,aes(factor(am),mpg))+geom_violin(aes(fill=factor(am)))+ylab("Miles per Gallon (MPG)")+scale_fill_discrete(name="Type",labels=c("Automatic","Manual"))+scale_x_discrete(name="",labels=c("Automatic","Manual"))+ggtitle(aes(title="MPG by transmission"))
library(dplyr)
ggplot(data=diamonds,aes(carat,price))+geom_point()+geom_smooth()+facet_wrap(~cut)
```