---
title: "STAT 321 Homework 4"
output: html_document
---
Charles Hwang

Professor Matthews

STAT 321-001

1 November 2019

## Exercise 18.4

```{r Exercise 18.4}
rm(list=ls())
set.seed(98)
o <- 0.1
t <- o + 0.3
s <- t + 0.6
plot(stepfun(0:5,c(o,o,o,t,t,t,s)),main="Exercise 18.4 CDF",ylab="P(X = x)")
f <- function(x = runif(1)){
  x <- c(0,0)
  x[1] <- runif(1)
  if (x[1] <= o){
    x[2] <- 1
  } else if (x[1] > o & x[1] <= t){
    x[2] <- 2
  } else if (x[1] > t){
    x[2] <- 5
  }
  cat("x =",x[1],"| X =",x[2])
  }
f(x)
```

## Exercise 18.12

```{r Exercise 18.12}
rm(list=ls())
set.seed(321)
# Because N is a discrete variable and the variance is unknown, a poisson distribution would be a good distribution for N.                                         # Exercise 18.12a
# Geometric distribution with p = 0.8                                       # Exercise 18.12b
# Y = sum(Xi)                                                               # Exercise 18.12c
N <- function(x = 10){rpois(1,x)}
n <- N()
X <- function(i = n){rgeom(i,0.8)}
Xi <- X()
Y <- function(x = Xi){sum(x)}
cat("N =",n,"\nXi =",Xi,"\nY =",Y())
#            ∞                            ∞
# P(Y = 0) = Σ dpois(i,10)*dgeom(i,0.8) = Σ (10^i*e^(-10)/i!)*(0.8^i) =     # Exercise 18.12d
#           i=0                          i=0
#                    ∞
# P(Y = 0) = e^-10 * Σ 8^i/i! ≈ 0.13533
#                   i=0
```

## Exercise 18.13

```{r Exercise 18.13}
rm(list=ls())

# ∫ 2(x-1)^2 dx =
# 2 ∫ (x^2-2x+1) dx =
# 2(x^3/3-x^2+x)
x <- seq(0,5,len=250)
y <- 2/3*x^3-2*x^2+2*x
plot(x,y,type="l")
```

## Exercise 18.14

```{r Exercise 18.14}
rm(list=ls())
# ∫ e^(-x)/(1+e^(-x))^2 dx =     # u = 1+e^(-x)
# ∫ -1/(u)^2 du =                # du = -e^(-x) dx
# 1/u =
# 1/(1+e^(-x))
```