---
title: "Homework 5"
output: html_document
---
Charles Hwang

Professor Matthews

STAT 388-001

12 November 2019

## Exercise 1

```{r Exercise 1, message=FALSE,warning=FALSE}
rm(list=ls())
train <- read.csv(file="/Users/newuser/Desktop/titanic/train.csv",header=TRUE)
test <- read.csv(file="/Users/newuser/Desktop/titanic/test.csv",header=TRUE)
train <- train[,-c(4,9,11)] # Removing categorical variables with large number of unique values ("Name", "Ticket", and "Cabin")
test <- test[,-c(3,8,10)]
library(car)
library(gbm)
library(glmnet)
library(ISLR)
library(plotmo)
library(randomForest)
library(rpart)
set.seed(811)
```

## Exercise 2

```{r Exercise 2}
tree <- rpart(Survived~.,method="class",data=train)
printcp(tree)
plotcp(tree)
plot(tree,uniform=TRUE,main="Classification Tree")
text(tree,use.n=TRUE,all=TRUE,cex=.8)
ptree <- prune(tree,cp=tree$cptable[which.min(tree$cptable[,"xerror"]),"CP"])
plot(ptree,uniform=TRUE,main="Pruned Classification Tree")
text(ptree,use.n=TRUE,all=TRUE)
treepred <- predict(tree,test,type="class")
table(treepred)
cat("Cross validation error:",min(tree$cptable[,"xerror"]))
```

## Exercise 3

```{r Exercise 3}
rf <- randomForest(as.factor(Survived)~.,data=train[!is.na(train$Age),],ntree=2000,importance=TRUE)
rf
# The out-of-bag cross-validation error is 17.79%.
rf3 <- randomForest(as.factor(Survived)~.,data=train[!is.na(train$Age),],ntree=2000,importance=TRUE,mtry=3)
rf6 <- randomForest(as.factor(Survived)~.,data=train[!is.na(train$Age),],ntree=2000,importance=TRUE,mtry=6)
plot(rf$err.rate[,1],type="l")
points(1:2000,rf3$err.rate[,1],type="l",col="red")
points(1:2000,rf6$err.rate[,1],type="l",col="blue")
varImpPlot(rf,main="Variable Importance Plot",cex=.7)
test <- rbind(train[1,-2],test) # See Stack Overflow for more information: https://stackoverflow.com/a/38097360
test <- test[-1,]
rfpred <- predict(rf,test,type="class")
table(rfpred)
summary(gbm(Survived~.,data=train[!is.na(train$Age),]))
rfpreddf <- as.data.frame(rep(0,length(rfpred))) # Exporting predictions to CSV file for Kaggle submission
rfpreddf$PassengerId <- test$PassengerId
rfpreddf$Survived <- rfpred
rfpreddf$`rep(0, length(rfpred))` <- NULL
Export(as.data.frame(rfpreddf),"Charles Hwang Submission.csv")
# Kaggle score: 290/418 (69.37799043% — nice!)
```