---
title: "STAT 351 Homework 1"
author: "Charles Hwang"
date: "1/21/2020"
output: html_document
---
Charles Hwang

Professor Matthews

STAT 351-001

24 January 2020

## Problem 1

```{r Problem 1}
testScores <- c(79,74,88,80,80,66,65,86,84,80,78,72,71,74,86,96,77,81,76,80,76,75,78,87,87,74,85,84,76,77,76,74,85,74,76,77,76,74,81,76)                                                            # Problem 1a
summary(testScores)
cat("There is initial evidence that the alternative hypothesis is true because the median is considerably greater than 70 (",median(testScores)," > 70).",sep="")
# H0: Median = 70                                                                 # Problem 1b
# HA: Median > 70
α = .05
binom.test(sum(testScores>70),length(testScores),alternative="greater")           # Problem 1c
cat("We reject H0 at α = ",α,". There is sufficient evidence (p = ",binom.test(sum(testScores>70),length(testScores),alternative="greater")$p.value,") that the median is greater than 70.",sep="") # Problem 1d
```

## Problem 2

```{r Problem 2}
library(MASS)
library(perm)
data <- data.frame(treatment=c(rep("1",4),rep("2",4)),obs=c(44,33,22,11,4,3,2,1))
permTS(data$obs~data$treatment,alternative="greater",exact=TRUE)$p.value
fractions(permTS(data$obs~data$treatment,alternative="greater",exact=TRUE)$p.value)
"For a permutation test in which all observations in one treatment are greater than all observations in the other, it is clear that the p-value is 1/choose(n,k). The only possible permutation that is as or more extreme than the value actually observed is the permutation that is precisely the same as the value actualy observed."
```

## Problem 3

```{r Problem 3, warning=FALSE}
siblings <- data.frame(hometown=c(rep("rural",24),rep("urban",17)),siblings=c(3,2,1,1,2,1,3,2,2,2,2,5,1,4,1,1,1,1,6,2,2,2,1,1,1,0,1,1,0,0,1,1,1,8,1,1,1,0,1,1,2))
# H0: r(t) = u(t) ∀ t (where r(t) is the distribution of the number of siblings in a rural hometown and u(t) is the distribution of the number of siblings in an urban hometown)      # Problem 3a
# HA: r(t) = u(t - Δ)
α = .05
wilcox.test(siblings$siblings~siblings$hometown,alternative="two.sided",correct=FALSE,exact=TRUE)
cat("We reject H0 at α = ",α,". There is sufficient evidence (p = ",wilcox.test(siblings$siblings~siblings$hometown,alternative="two.sided",correct=FALSE,exact=TRUE)$p.value,") that the distributions of the number of siblings in rural and urban hometowns are different using a Wilcoxon rank-sum test.",sep="")
permTS(siblings$siblings~siblings$hometown,alternative="two.sided") # Problem 3b
cat("We fail to reject H0 at α = ",α,". There is insufficient evidence (p = ",permTS(siblings$siblings~siblings$hometown,alternative="two.sided")$p.value,") that the distributions of the number of siblings in rural and urban hometowns are different using a permutation test.",sep="")
```

## Problem 4

```{r Problem 4, warning=FALSE}
data <- data.frame(y=c(rep("1",4),rep("2",4)),x=c(6,5,5,3,4,3,2,1))
wilcox.test(data$x~data$y,alternative="two.sided",correct=FALSE,exact=TRUE)
t.test(data$x~data$y,alternative="two.sided")
cat("P-value (Wilcoxon rank-sum test): ",wilcox.test(data$x~data$y,alternative="two.sided",correct=FALSE,exact=TRUE)$p.value,"\n     P-Value (Two-sample t-test): ",t.test(data$x~data$y,alternative="two.sided")$p.value,sep="")
```