---
title: "Homework 4"
author: "Charles Hwang"
date: "2/27/2020"
output: html_document
---
Charles Hwang

Professor Matthews

STAT 351-001

16 March 2020

## Problem 1

```{r Problem 1}
rm(list=ls())
mat <- matrix(c(4,9,3,0),ncol=2)
rownames(mat) <- c("Low","High")
colnames(mat) <- c("Nearby","Not Nearby")
mat
fisher.test(mat)
cat("We fail to reject H0 at α = .05. There is insufficient evidence (p = ",fisher.test(mat)$p.value,") that there is a significant assocation between contamination and distance.",sep="")
```

## Problem 3

```{r Problem 3, warning=FALSE}
rm(list=ls()) # Chi-squared test warnings turned off to reduce clutter
library(gtools)
library(perm)
mat <- matrix(c(4,5,14,7),ncol=2)
rownames(mat) <- c("Made First","Missed First")
colnames(mat) <- c("Made Second","Missed Second")
mat
mcnemar.test(mat)         # Problem 3a
cat("We fail to reject H0 at α = .05. There is insufficient evidence (p = ",mcnemar.test(mat)$p.value,") that there the probability of making a shot on the first attempt is different than the probability of making a shot on the second attempt.",sep="")
chisq.test(mat)$statistic # Problem 3b
chisq.test(mat)$p.value
as.data.frame(as.table(mat))

cat("This p-value (p = ",chisq.test(mat)$p.value,") is greater than the p-value for McNemar's test (p = ",mcnemar.test(mat)$p.value,"). We fail to reject H0 at α = .05. There is insufficient evidence that there the probability of making a shot on the first attempt is different than the probability of making a shot on the second attempt.",sep="")
```

## Problem 4

```{r Problem 4, message=FALSE}
rm(list=ls())
library(boot)
library(tree)
summary(nuclear)
help(nuclear)
T <- tree(cost~.,data=nuclear)
T
predict(T)
plot(T)
text(T)
```

## Problem 5

```{r Problem 5, message=FALSE}
library(randomForest)
set.seed(1603)
rf <- randomForest(cost~.,data=nuclear,ntree=15000,importance=TRUE)
predict(rf,nuclear)
varImpPlot(rf,main="Variable Importance Plot",cex=.7) # Adding some graphs to visualize the random forest
plot(rf$mse,type="l")
plot(nuclear$cost,ylab="Construction cost (millions of dollars, 1976)")
points(predict(rf,nuclear),pch=0,col="green")
points(predict(T),pch=2,col="brown") # Comparing CART model with actual values and random forest
legend(0,900,c("Actual Values","Predicted (RF)","Predicted (CART)"),col=c("black","green","brown"),pch=c(1,0,2)) # The five terminal nodes of the CART are seen in the brown triangular points plotted horizontally along five distinct imaginary lines, each representing the value of a terminal node.
```