---
title: "STAT 351 Homework 5"
author: "Charles Hwang"
date: "3/27/2020"
output: html_document
---
Charles Hwang

Professor Matthews

STAT 351-001

30 March 2020

## Problem 1

```{r Problem 1}
rm(list=ls())
kcTemp <- c(43.8,40.1,49.2,41.8,34.0,49.1,47.8,48.1,37.6,42.0,43.7,47.1,47.7,46.9,36.5,45.0,48.0,37.6,42.2,38.7,45.2,42.5,43.1,36.0,47.4,48.5,47.1,43.2,43.8,45.7)
hist(kcTemp,freq=FALSE,main="Average March Temperature in Kansas City, 1961-90",xlab="Temperature (in degrees Fahrenheit)")
legend(34,.12,c("Δ = 2.309091","Δ = 2.193618"),lwd="1",col=c("black","blue"))
points(density(kcTemp,bw=1.06*sd(kcTemp)/length(kcTemp)^.2)$x,density(kcTemp,bw=1.06*sd(kcTemp)/length(kcTemp)^.2)$y,type="l")
points(density(kcTemp,bw=1.06*IQR(kcTemp)/(1.34*length(kcTemp)^.2))$x,density(kcTemp,bw=1.06*IQR(kcTemp)/(1.34*length(kcTemp)^.2))$y,type="l",col="blue") # Nearly the same as the other kernel
cat("Either one of Hardle's two standards for Δ works well for this histogram.")
```

## Problem 2

```{r Problem 2}
rm(list=ls())
data <- read.csv(file="/Users/newuser/Desktop/HW6stateData.csv",header=TRUE)
plot(data$Income~data$HS.Grad)                          # Problem 2a
summary(lm(data$Income~data$HS.Grad))                   # Problem 2b
plot(data$Income~data$HS.Grad)
legend(37,6350,"Linear Regression Line (r^2 = .3715)",lwd="1")
lines(sort(data$HS.Grad),fitted(lm(data$Income~data$HS.Grad))[order(data$HS.Grad)])
summary(lm(data$Income~data$HS.Grad+I(data$HS.Grad^2))) # Problem 2c
plot(data$Income~data$HS.Grad)
legend(37,6350,c("Linear Regression Line (r^2 = .3715)","Quadratic Regression Line (r^2 = .38)"),lwd="1",col=c("black","red"))
lines(sort(data$HS.Grad),fitted(lm(data$Income~data$HS.Grad))[order(data$HS.Grad)])
lines(sort(data$HS.Grad),fitted(lm(data$Income~data$HS.Grad+I(data$HS.Grad^2)))[order(data$HS.Grad)],col="red")
summary(loess(data$Income~data$HS.Grad))                # Problem 2d
plot(data$Income~data$HS.Grad)
legend(37,6350,c("Linear Regression Line (r^2 = .3715)","Quadratic Regression Line (r^2 = .38)","LOESS Line (RSE = 462.7)"),lwd="1",col=c("black","red","blue"))
lines(sort(data$HS.Grad),fitted(lm(data$Income~data$HS.Grad))[order(data$HS.Grad)])
lines(sort(data$HS.Grad),fitted(lm(data$Income~data$HS.Grad+I(data$HS.Grad^2)))[order(data$HS.Grad)],col="red")
lines(sort(data$HS.Grad),fitted(loess(data$Income~data$HS.Grad))[order(data$HS.Grad)],col="blue")
# "lines(sort(data$HS.Grad),loess(data$Income~data$HS.Grad)$fitted[order(data$HS.Grad)],col="blue")" also produces the same line
cat("The linear and quadratic lines are very similar and fit the data with weak to fair strength. The LOESS line fits the data better but is not radically different than the other two lines. The three lines would be more similar to one another if the two outliers (the rightmost points) were removed.")
```

## Problem 3

```{r Problem 3}
rm(list=ls())
set.seed(1234)
x <- runif(100,0,10)
y <- sin(x) + rnorm(100,0,.3)
plot(x,y)
summary(loess(y~x))
plot(x,y)
legend(-.15,-.5,c("Span = 0.75","Span = 0.6","Span = 0.25"),lwd="1",col=c("black","red","blue"))
lines(sort(x),fitted(loess(y~x))[order(x)])
lines(sort(x),fitted(loess(y~x,span=.6))[order(x)],col="red")
lines(sort(x),fitted(loess(y~x,span=.25))[order(x)],col="blue")
cat("It appears that [0.25, 0.6] would be a good range of spans to construct a LOESS model for this data. Any line with span > 0.75 would be too smooth for a reasonable fit, as it largely ignores the second cycle in the data. Even the line with the default span = 0.75 is a bit too smooth because the sinusoidal nature of the data makes it difficult to perform LOESS on a large number of observations (k = ",.75*length(x),"). The line with span = 0.6 would be the maximum span to construct a reasonable LOESS model, and the line with span = 0.25 would be the minimum span to ensure the line does not become too jagged.",sep="")
```