---
title: "STAT 351 Homework 3"
author: "Charles Hwang"
date: "2/11/2020"
output: html_document
---
Charles Hwang

Professor Matthews

STAT 351-001

21 February 2020

## Problem 1

```{r Problem 1}
rm(list=ls())
library(perm)
dat <- data.frame(kg=c(1.5,2.1,1.9,2.8,1.4,1.8,1.8,2.0,2.0,2.7,1.6,2.3,1.9,2.5,2.5,2.6,2.1,2.4),date=factor(rep(c("Sept 1","Sept 15","Sept 30"),each=6)),block=factor(rep(1:6,3)))
dat
permKS(dat$kg~dat$date,exact=TRUE,control=permControl(nmc=90000,p.conf.level=.95)) # Problem 1a
friedman.test(dat$kg,dat$date,dat$block)                                           # Problem 1b
anova(lm(kg~date,data=dat))                                                        # Problem 1c
cat("The p-value for ANOVA (p = ",anova(lm(kg~date,data=dat))["date","Pr(>F)"],") is higher than the p-value for the Friedman's test (p = ",friedman.test(dat$kg,dat$date,dat$block)$p.value,"), but slightly lower than the p-value for the permutation test (p = ",permKS(dat$kg~dat$date,exact=TRUE,control=permControl(nmc=90000,p.conf.level=.95))$p.value,").",sep="")
# H0: There is no difference between the two means being compared                  # Problem 1d
# HA: There is a difference between the two means being compared
α = .05
TukeyHSD(aov(lm(kg~date,data=dat)))
plot(TukeyHSD(aov(lm(kg~date,data=dat))))
cat("The differences between Sept 1 and Sept 15 (p = ",TukeyHSD(aov(lm(kg~date,data=dat)))$date[1,"p adj"],"), Sept 1 and Sept 30 (p = ",TukeyHSD(aov(lm(kg~date,data=dat)))$date[2,"p adj"],"), and Sept 15 and Sept 30 (p = ",TukeyHSD(aov(lm(kg~date,data=dat)))$date[3,"p adj"],") all fail to reject H0 for Tukey's HSD procedure at α = ",α,".",sep="")
```

## Problem 3

```{r Problem 3}
rm(list=ls())
age <- c(3,7,15,24,85,180,360)
strength <- c(2500,3200,4300,5300,5900,6700,6900)
plot(age,strength)                                                         # Problem 3a
cor(age,strength,method="pearson")
cor(age,strength,method="spearman")
cor(age,strength,method="kendall")
# H0: There is no or an insignificant association between age and strength # Problem 3b
# HA: There is a significant association between age and strength
α = .05
cor.test(age,strength,method="spearman")
cat("We reject H0 at α = ",α,". There is sufficient evidence (p = ",cor.test(age,strength,method="spearman")$p.value,") that there is a significant association between age and strength.",sep="")
```

## Problem 4

```{r Problem 4}
rm(list=ls())
set.seed(2102)
eosinophil <- c(55,140,91,122,111,185,203,101,76,145,95,101,196,45,299,226,65,70,196,72,121,171,151,113,112,67,276,125,100,81,122,71,158,78,162,128,96,79,67,119)
n <- 10000 # Problem 4a
BSμ <- rep(NA,n)
for (i in 1:n){
  BSμ[i] <- mean(eosinophil[sample(1:length(eosinophil),length(eosinophil),replace=TRUE)])
}
mean((BSμ-mean(eosinophil))^2) # Bootstrap estimate of MSE
var(eosinophil)/length(eosinophil) # Compare bootstrap estimate to true value
sd(BSμ) # Bootstrap estimate of standard error
BSσ <- rep(NA,n) # Problem 4b
for (i in 1:n){
  BSσ[i] <- sd(eosinophil[sample(1:length(eosinophil),length(eosinophil),replace=TRUE)])
}
mean((BSσ-sd(eosinophil))^2) # Bootstrap estimate of MSE
sd(eosinophil) # Compare bootstrap estimate to true value
sd(BSσ) # Bootstrap estimate of standard error
BS95 <- rep(NA,n) # Problem 4c
for (i in 1:n){
  BS95[i] <- quantile(eosinophil[sample(1:length(eosinophil),length(eosinophil),replace=TRUE)],.95)
}
mean((BS95-quantile(eosinophil,.95))^2) # Bootstrap estimate of MSE
quantile(eosinophil,.95) # Compare bootstrap estimate to true value
sd(BS95) # Bootstrap estimate of standard error
```

## Problem 5

```{r Problem 5}
rm(list=ls())
set.seed(2102)
n = 15 # Problem 5a
μ = 5
v = 36
sample <- rnorm(n,μ,v)
mean(sample) # Problem 5b
v/n # Problem 5c
sim <- 10000 # Problem 5d
BSv <- rep(NA,sim)
for (i in 1:sim){
  BSv[i] <- var(sample[sample(1:n,n,replace=TRUE)])/n
}
mean((BSv-var(sample)/n)^2)
```