---
title: "Exam"
output: pdf_document
---
Charles Hwang

Professor Matthews

STAT 321-001

18 October 2019

## Problem 1

```{r Problem 1}
rm(list=ls())
y <- function(n) {   # Problem 1a
  sort(sample(1:6,n,replace=TRUE),decreasing=FALSE)
  }
y(5)
i <- 1
while (i >= 1 & i <= 10000) { # Problem 1b
  x <- sort(unique(sample(1:6,5,replace=TRUE)))
  c <- 0
  if(length(x) == 4 & x[1] == x[2]-1 & x[2] == x[3]-1 & x[3] == x[4]-1) {
  c <- c + 1
  i <- i + 1
  } else {
    i <- i + 1
  }
}
c
3*4/6^4
while (i >= 1 & i <= 10000) { # Problem 1c
  x <- sort(sample(1:6,5,replace=TRUE))
  c <- 0
  if(length(x) == 5) {
  c <- c + 1
  i <- i + 1
  } else {
    i <- i + 1
  }
}
c
while (i >= 1 & i <= 10000) { # Problem 1d
  x <- sort(unique(sample(1:6,5,replace=TRUE)))
  c <- 0
  if(length(x) == 5 & sum(x) != 15 & sum(x) != 20) {
  c <- c + 1
  i <- i + 1
  } else {
    i <- i + 1
  }
}
c
4*6/6^5
```

## Problem 2

```{r Problem 2}
rm(list=ls())
f <- function(x) {
  sin(exp(x))+cos(exp(-x))
}
curve(f,xlim=c(-3,0))
abline(h=0)

sm <- function(f,x0,x1,t=.0001,n=9) {
  for (i in 1:n) {
    x2 <- x1-f(x1)*(x1-x0)/(f(x1)-f(x0))
    if (abs(x2-x1)<t) {
      return(x2)
      }
    x0 <- x1
    x1 <- x2
  }
}
c(sm(f,-2.75,-2.5),sm(f,-2.5,-2.25),sm(f,-2.25,-2),sm(f,-1.75,-1.25),sm(f,-1,-0.5))
```

## Problem 3

```{r Problem 3, eval=FALSE}
rm(list=ls())
A <- 8675309
B <- 987654321
m <- 2^32
x <- c()
x[1] <- 1234567890
MT <- function(y,A,B,m) {
  return((A*y+B)%%m)
  }
MT(runif(1000),8675309,987654321,2^32)/m # Output suppressed
```

## Problem 4

```{r Problem 4, eval=FALSE}
f <- function(y,a=1) {
  (-log(y))^(-1/a) # Inverse: (-log(y))^(-1/a)
  }
f(runif(1000))     # Output suppressed
```

## Problem 5

```{r Problem 5}
rm(list=ls())
A <- 8675309           # Data and function from problem 3
B <- 987654321
m <- 2^32
x <- c()
x[1] <- 1234567890
MT <- function(y,A,B,m) {
  return((A*y+B)%%m)
  }
f <- function(y,a=1) { # Function from problem 4
  (-log(y))^(-1/a)
  }

for (i in 1:1000) {
  x[i+1] <- MT(x[i],A,B,m)
  }
data <- x/m
one <- f(data)
two <- f(data,a=2)
thr <- f(data,a=3)
fou <- f(data,a=4)
fiv <- f(data,a=5)
six <- f(data,a=6)
par(mfrow=c(3,2))
hist(one,main="a=1",xlab="Distribution",xlim=c(0,25),breaks=5000)
hist(two,main="a=2",xlab="Distribution",xlim=c(0,10),breaks=320)
hist(thr,main="a=3",xlab="Distribution",xlim=c(0,10),breaks=80)
hist(fou,main="a=4",xlab="Distribution",xlim=c(0,10),breaks=40)
hist(fiv,main="a=5",xlab="Distribution",xlim=c(0,10),breaks=20)
hist(six,main="a=6",xlab="Distribution",xlim=c(0,10),breaks=20)
```